{{- range .Values.storageClasses }}
{{- if .enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "csi-driver-lvm.storageclass.fullname" (dict "global" $ "storageclass" .) }}
{{- if not (empty .additionalAnnotations) }}
  annotations:
    {{- .additionalAnnotations | toYaml | nindent 4 -}}
{{- end }}
  labels: {{- include "csi-driver-lvm.labels" $ | nindent 4 }}
provisioner: {{ include "csi-driver-lvm.csi-driver.fullname" $ }}
reclaimPolicy: {{ .reclaimPolicy }}
volumeBindingMode: {{ default "WaitForFirstConsumer" .volumeBindingMode }}
allowVolumeExpansion: true
parameters: {{ include "csi-driver-lvm.storageclass.parameters" (dict "global" $ "storageclass" .) | nindent 2 }}
---

{{- if and .parameters.encryption (eq .parameters.encryption "true" ) }}

{{- $secretName := (include "csi-driver-lvm.storageclass.encryption.secret.fullname" (dict "global" $ "storageclass" .)) }}
{{- if not (empty (index .parameters "csi.storage.k8s.io/node-stage-secret-name")) }}
{{- $secretName := (index .parameters "csi.storage.k8s.io/node-stage-secret-name") }}
{{- end }}

{{- $secretNamespace := (include "csi-driver-lvm.storageclass.encryption.secret.namespace" (dict "global" $ "storageclass" .)) }}
{{- if not (empty (index .parameters "csi.storage.k8s.io/node-stage-secret-namespace")) }}
{{- $secretNamespace := (index .parameters "csi.storage.k8s.io/node-stage-secret-namespace") }}
{{- end }}

{{- $oldSecret := (lookup "v1" "Secret" $secretNamespace $secretName) }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $secretNamespace }}
  labels: {{- include "csi-driver-lvm.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- if not (empty .passphrase) }}
  passphrase: {{ .passphrase | b64enc | quote }}
  {{- else }}
  {{- if $oldSecret }}
  passphrase: {{ $oldSecret.data.passphrase }}
  {{- else }}
  passphrase: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- end }}
---
{{- end }}

{{- end }}
{{- end }}